apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-dev

namePrefix: dev-

bases:
- ../../base
- namespace.yaml

patches:
- path: patch-replicas.yaml
- path: patch-configmap.yaml

commonLabels:
  env: dev

images:
- name: nginx
  newTag: "1.25"
